using System;
using System.Core;
using LeoLang;

public enum color {
	red,
	blue,
	green,
};

enum symboltable : string {
	identifier,
	unknown
};

int Main(string[] args) {
	var fff = true;

	if(true) {
		return 1;
	};
	
	var xml = dom { <xml><child /></xml> };

	return 0;
};

public int GetAwnser(void) {
	return 42;
};

void lowestTest(void) {
		var x = :hello;
		return;
};

struct myData {
	field double PI = 3.14;
};